---
title: "La démarche"
editor: visual
---

### Pourquoi ?

Les mathématiques associées à l'informatique sont omniprésentes dans tous les domaines de l'activité humaine. Pourtant, de moins en moins de lycéens et encore moins de lycéennes choisissent de poursuivre les mathématiques dans les options de première et de terminale. Cette tendance risque d'accentuer la sous-représentation des femmes dans les métiers liés aux mathématiques et plus généralement au numérique, suscitant de vives inquiétudes sur les questions de **parité** hommes-femmes dans ces domaines.

Par ailleurs, la crise climatique et l'effondrement de la biodiversité nécessitent de former les jeunes générations pour répondre aux enjeux et aux défis en cours et à venir. Les mathématiques et l'informatique font partie des outils indispensables pour aborder ces questions.

Le projet des Mouettes Savantes vise à sensibiliser les lycéennes sur l'intérêt de la modélisation mathématique et sa mise en oeuvre informatique pour faire face aux enjeux écologiques et environnementaux.

### Pour qui ?

Un groupe de 30 lycéennes, en classe de seconde, issues de lycées d'Ile de France Sud, d'ille et Vilaine et du Finistère qui souhaitent découvrir l'application des mathématiques et de l'informatique en écologie et en environnement.

### Quand ?

Du 16 au 20 juin 2025

### Où ?

Les activités scientifiques auront lieu à [la station biologique de Paimpont](https://paimpont.univ-rennes.fr/) en forêt de Brocéliande (centre Bretagne). Les participantes seront hébergées dans les chalets du [camping de paimpont](https://www.camping-paimpont-broceliande.com/les-chalets/).

### Pour y faire quoi ?

La journée type propose une matinée autour de questions scientifiques et des après-midis sportives ou de découverte de la forêt de Brocéliande.

Durant les temps dédiés aux activités scientifiques, les lycéennes s'organisent en petits groupes pour construire une réponse à un problème lié à des questions écologiques ou environnementales ([les projets de 2024](mouettes2024.html))

A l'issue de la semaine, Les participantes restitueront leurs travaux sous la forme d'un poster, d'une vidéo, d'un podcast ou de tout autre support de leur choix, ce qui leur permettra de partager l'expérience avec leur entourage au lycée ou dans le milieu familial.

### Avec qui ?

Le projet est coordonné par des chercheuses et enseignantes chercheuses :

-   [Anna Bonnet](https://anna.biogeek.land/) : maître de conférences à Sorbonne Université, spécialiste de l'inférence statistique des processus ponctuels

-   [Sophie Donnet](https://sophiedonnet.github.io/) : directrice de recherche à INRAE, spécialiste de la modélisation des interactions entre espèces

-   [Marie-Pierre Etienne](https://marieetienne.github.io/) : maître de conférences à L'Institut Agro Rennes-Angers, spécialiste de l'écologie du mouvement

-   [Juliette Legrand](https://juliettelegrand.netlify.app/) : maître de conférences à L'Universite de Bretagne Occidentale, spécialiste des modèles de valeurs extrêmes, notamment dans un contexte climatique et océanographique

-   [Marie Perrot-Dockès](https://marie-perrotdockes.github.io/) : maître de conférences à L'Universite de Paris, spécialiste des données en grande dimension, notamment dans les applications médicales

D'autres intervenants, doctorantes ou doctorants, chercheuses ou chercheurs, enseignantes ou enseignants participeront à l'encadrement des projets durant la semaine.

Par ailleurs, la vie quotidienne et les animations seront encadrés par des professionnels de l'animation titulaires du BAFA ou BAFD (et pour certaines engagées dans des études de mathématiques)

### Nous contacter

Pour toute demande de renseignement, vous pouvez contacter les organisatrice [par mail](mailto:lesmouettessavantes@gmail.com).

### Des cigales, des cigognes, des fourmis et des marmottes

De nombreux séjours visent à prouver aux femmes que les mathématiques c'est aussi pour elles. On peut citer entre notamment

-   [Les Cigales dans le Sud](https://www.fr-cirm-math.fr/lescigales.html)
-   [Les Cigognes en Grand Est](https://iecl.univ-lorraine.fr/cigognes/)
-   [Les Fourmis dans le Nord](https://apmeplille.fr/les-fourmis.html)
-   [Les Marmottes en Suisse](https://swissmaprs.ch/events/lesmarmottes2023/)
